### ISSUE TITLE
success notification location

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [andy-portmen/ecleaner#5]
If the display/window/doorhanger (what do you call this exactly?) is not kept open, then no notification is ever seen. Just losing application focus, or changing to a new tab, or clicking anywhere outside the display area causes it to be closed.

See: https://addons.mozilla.org/en-US/firefox/addon/empty-cache-button/ images 2 and 3 for a solution. It would be preferable/nice to include an option to display the notification or not :)

**Comment by andy-portmen** [comment]
The "done" message is shown for 500 msecs before panel gets closed. I think it looks good and there is no need for the desktop notification. After updating to 0.1.3, you can reopen if this is still not clear enough.

**Comment by Thorin-II** [comment]
I'll certainly be testing it :) Maybe it's because of #4 (I have yet to see a success/done message) that I've misunderstood this. But now that's fixed, I'll revisit when it lands. Thanks

PS: In our repo (which is about Firefox about:config tweaks), we also have a few wiki pages on various related things, such as recommended addons for privacy/security - and with the whole move to Web Extensions, our [Wiki recommended add-ons list](https://github.com/ghacksuserjs/ghacks-user.js/wiki/Appendix-B:-Firefox-Add-ons) is in the process of being updated as suitable WE's become available. We (Gitoffthelawn from issue 2 is also a collaborator) have kept on eye on this for a while. Thanks for developing it, and drop by some time :)
